### ISSUE TITLE
RuntimeError: Python version >= 3.6 required running sdist

### ISSUE THREAD

**Issue by rolyp** [datasig-ac-uk/esig#52]
The source distribution script `sdist` no longer seems to work. Unfortunately, Googling for the error message produces zero hits.
- [x] name specific `Cython` version used in last successful build :x: didn’t help
- [x] bump Python version to 3.6 in GitHub runner

**Comment by terrylyons** [comment]
Can’t you roll back the repository? I thought it was all working?

**Comment by rolyp** [comment]
@terrylyons A fully reproducible build is the goal, but it seems to be hard to achieve in practice. Virtual machines and containers aren’t closed systems: commands like `apt-get install` and `pip install` interact with the outside world, and so you need to take care to name versions of software as explicitly as possible to achieve anything resembling reproducibility. Vendors also update containers and virtual machines to apply security patches. True reproducibility remains elusive, as we saw when we tried to pick up where Nick left off.

I don’t know what caused this particular obsolescence. I tried setting `Cython` to a specific version, since `sdist` relies on that, but that didn’t help. I ended up just bumping the Python version on the workflow configuration to 3.6, which will do for now, but doesn’t protect us against future problems of this kind.
