### ISSUE TITLE
recombine integration (64-bit Linux)

### ISSUE THREAD

**Issue by rolyp** [datasig-ac-uk/esig#54]
Remaining `linux-pyXX-64bit` tasks
- <s>`27`: `/opt/python/cp27-cp27m/bin/python`: No such file or directory</s>
- <s>`27u`: `/opt/python/cp27-cp27mu/bin/python`: No such file or directory</s>
- <s>`34`: `/opt/python/cp34-cp34m/bin/python`: No such file or directory</s>
- [x] `37`: `ModuleNotFoundError`: No module named `wheel.wheelfile` – needs [`wheel==0.34.2`](https://github.com/pypa/manylinux/issues/512)
- integrate Terry’s `PyTestRecombine.py` into `esig/tests` as `recombinetests.py`
  - [x] switch formatting to format strings rather than Python 3.6-style string interpolation
  - <s>break into 3 separate tests</s> – not easy (shared prepared data), but emit test number for clarity
  - check tests run on:
    - <s>`mac-py27` :x: `ImportError: cannot import name tests` (importing esig tests into recombine)</s>
    - <s>`mac-py34` :x: `ImportError: cannot import name tests` (importing esig tests into recombine)</s>
    - [x] `mac-py35`
    - [x] `mac-py36` :x: test2 fails with `no of points left =  2401` – determinise by fixing random seed
    - [x] `mac-py37`
    - [x] `mac-py38`
    - [ ] `linux-py3[5--8]-64bit` :x: process killed
      - [x] run OMP configuration script :x: no change
      - [x] verify OMP environment variables still set in `virtualenv` for tests
      - [x] bump Docker daemon memory from 8Gb to 16Gb – ✅  yes, fixes local problem
      - still failing in GitHub Runner
        - <s>set `--memory=16g` on Docker command-line</s> :x: doesn’t help
        - [x] as per comment, set `dimension = 240` for a “small” test

Occasionally, installation of `sudo` fails with `[Errno -1] repomd.xml does not match metalink for epel`, but this seems to be a sporadic networking failure.
***
Done/dropped:

Compilation:
- [x] `error: ‘for’ loop initial declarations are only allowed in C99 mode` – add `-std=c99` to `extra_compile_args` in `install_helpers.py` (assumes `gcc`)
- `error: ’nullptr’ was not declared in this scope` 
  - [x] replace `nullptr` by `NULL` for now
- [x] error: `This file requires compiler and library support for the ISO C++ 2011 standard.`
  - [x] replace `c99` by `c++11` in above
  - [x] fix `c99` error by refactoring `for` loops
- [x] `‘ptrdiff_t’ does not name a type` in `lapack_fortran_definitions.h` – include `stddef.h`
- [x] call `doall-linux.sh` build script for `recombine` from esig `build-wheel.sh` 
`auditwheel` step to pick up `recombine`:
- [x] `auditwheel show` to check dependency on `recombine` not yet present
- [x] add `recombine` to `used_libraries` in `install_helpers.py`
- `ld: cannot find -lrecombine` (as expected)
  - [x] add `$HOME/lyonstech/lib` to `library_dirs` in `install_helpers.py` :x: not visible inside Docker container
  - <s>move `doall-linux.sh` step to Dockerfile</s> – sounds like more opacity I don’t need
  - run `doall-linux.sh` inside Docker container 
    - `wget` fails with `Unable to establish SSL connection` – probably [problem with `manylinux`](https://github.com/pypa/manylinux/issues/202)
    - [x] switch Linux build of `recombine` so it only uses `curl`, not `wget`
    - `apt-key` fails (`manylinux` uses `yum`, not `apt`) – migrated `recombine` to `manylinux2014`
  - run `doall-linux.sh` outside Docker container
    - [x] copy `.so` files to location visible to container
      - [x] `cp` fails with exit code 1 without `-r` if source contains a directory
- [x] examine output of `auditwheel show` (see below)
- <s>`skipping incompatible /data/build/lib//librecombine.so when searching for -lrecombine`</s> – 32-bit only
- [x] `Cannot repair wheel, because required library “librecombine.so.1” could not be located`
  - [x] set `LD_LIBRARY_PATH=/data/build/lib:$LD_LIBRARY_PATH` in `setup.py` :x: wrong environment?
  - [x] set in `linux_wheel_builder.sh` instead
  - [x] no longer need explicit inclusion of `/data/build/lib` into `library_dirs`?
- <s>check audited wheel is consistent with platform tag `manylinux1_x86_64` (see below)</s>
- `error: cannot repair “tmp/esig-0.7.1-cp34-cp34m-linux_x86_64.whl” to “manylinux1_x86_64” ABI because of the presence of too-recent versioned symbols`
  - [x] get `recombine` building on `manylinux14` (terrylyons/recombine#19)
  - [x] `esig` to build `recombine` using `doall-manylinux.sh` (now uses Docker container to build)
  - `cannot access ‘/home/runner/lyonstech/lib64’: No such file or directory`
    - `recombine` builder is installing to a home directory inside the `recombine` Docker container
      - pull `make install` step out of `doall.sh` and [specify install dir](https://stackoverflow.com/questions/3239343/make-install-but-not-to-default-directories/17679654#17679654) explicitly? :x: `make install` fails with `/usr/lib64/python2.7/site-packages/cmake/data/bin/cmake: No such file or directory` (installer depends on something inside Docker container?)
      - [x] first migrate `esig` to `manylinux2014`
      - [x] build `recombine` local image and have `esig` Docker file extend that
***
````
+ auditwheel show tmp/esig-0.7.1-cp37-cp37m-linux_x86_64.whl

esig-0.7.1-cp37-cp37m-linux_x86_64.whl is consistent with the
following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libgcc_s.so.1 with versions {'GCC_3.0'},
libc.so.6 with versions {'GLIBC_2.4', 'GLIBC_2.2.5', 'GLIBC_2.14',
'GLIBC_2.16'}, libm.so.6 with versions {'GLIBC_2.2.5'}, libstdc++.so.6
with versions {'GLIBCXX_3.4', 'CXXABI_1.3'}, libpthread.so.0 with
versions {'GLIBC_2.3.2', 'GLIBC_2.2.5'}, libdl.so.2 with versions
{'GLIBC_2.2.5'}, libiomp5.so with versions {'VERSION'}

This constrains the platform tag to "manylinux2014_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
````

**Comment by rolyp** [comment]
Will deal with 32-bit builds as #57.

**Comment by terrylyons** [comment]
Roly I am thinking about 32 bit builds now. Have not yet touched the code. Recombine needs changing in two ways.

First, the build needs different compiler switches, paths, and libraries and the ilp is changed to lp.

Secondly we need to check the environmental variables inside the code switch the integer type to 32 bit; I expect they will be fine.

Terry

On 6 Jul 2020, at 19:17, Roly Perera <notifications@github.com> wrote:

﻿

Will deal with 32-bit builds as #57<https://github.com/datasig-ac-uk/esig/issues/57>.
