### ISSUE TITLE
sdist failing with "RuntimeError: Python version >= 3.7 required.”

### ISSUE THREAD

**Issue by rolyp** [datasig-ac-uk/esig#81]
E.g. https://github.com/datasig-ac-uk/esig/runs/1680716728?check_suite_focus=true.

**Comment by rolyp** [comment]
Comment from @terrylyons:

> Help, I am struggling. I tried to install esig on Havok; the default py3 is 3.6.– it doesn’t install!!! This is terrible. What is happening. Best Terry PS at the end there is a separate email about manylinux – I was actually going to download the wheel and try auditwheel on it….,
> 
> Best
> 
>  
> 
> Terry
> 
>  
> 
> havok:testmanylinuxesig% python3 -m venv py3
> 
> havok:testmanylinuxesig% source py3/bin/activate
> 
> (py3) havok:testmanylinuxesig% python -V
> 
> Python 3.6.9
> 
> (py3) havok:testmanylinuxesig% pip install esig
> 
> Collecting esig
> 
>   Cache entry deserialization failed, entry ignored
> 
>   Cache entry deserialization failed, entry ignored
> 
>   Downloading https://files.pythonhosted.org/packages/bf/53/8824eff48de16dcfa65ab2655f03fcf541efd6749090acb6dde837a842c2/esig-0.8.2.tar.gz (92kB)
> 
>     100% |████████████████████████████████| 92kB 3.3MB/s
> 
>     Complete output from command python setup.py egg_info:
> 
>     esig_install> Starting esig installer…
> 
>     Traceback (most recent call last):
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 154, in save_modules
> 
>         yield saved
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 195, in setup_context
> 
>         yield
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 250, in run_setup
> 
>         _execfile(setup_script, ns)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 45, in _execfile
> 
>         exec(code, globals, locals)
> 
>       File “/tmp/easy_install-0mb05pjc/numpy-1.20.0rc2/setup.py”, line 30, in <module>
> 
>         """
> 
>     RuntimeError: Python version >= 3.7 required.
> 
>  
> 
>     During handling of the above exception, another exception occurred:
> 
>  
> 
>     Traceback (most recent call last):
> 
>       File “<string>“, line 1, in <module>
> 
>       File “/tmp/pip-build-9h7akhs4/esig/setup.py”, line 148, in <module>
> 
>         ‘build_ext’: BuildExtensionCommand,
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/__init__.py”, line 128, in setup
> 
>         _install_setup_requires(attrs)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/__init__.py”, line 123, in _install_setup_requires
> 
>         dist.fetch_build_eggs(dist.setup_requires)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/dist.py”, line 513, in fetch_build_eggs
> 
>         replace_conflicting=True,
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 774, in resolve
> 
>         replace_conflicting=replace_conflicting
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 1057, in best_match
> 
>         return self.obtain(req, installer)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 1069, in obtain
> 
>         return installer(requirement)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/dist.py”, line 580, in fetch_build_egg
> 
>         return cmd.easy_install(req)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/command/easy_install.py”, line 698, in easy_install
> 
>        return self.install_item(spec, dist.location, tmpdir, deps)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/command/easy_install.py”, line 724, in install_item
> 
>         dists = self.install_eggs(spec, download, tmpdir)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/command/easy_install.py”, line 909, in install_eggs
> 
>         return self.build_and_install(setup_script, setup_base)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/command/easy_install.py”, line 1177, in build_and_install
> 
>         self.run_setup(setup_script, setup_base, args)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/command/easy_install.py”, line 1163, in run_setup
> 
>         run_setup(setup_script, args)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 253, in run_setup
> 
>         raise
> 
>       File “/usr/lib/python3.6/contextlib.py”, line 99, in __exit__
> 
>         self.gen.throw(type, value, traceback)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 195, in setup_context
> 
>         yield
> 
>       File “/usr/lib/python3.6/contextlib.py”, line 99, in __exit__
> 
>         self.gen.throw(type, value, traceback)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 166, in save_modules
> 
>         saved_exc.resume()
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 141, in resume
> 
>         six.reraise(type, exc, self._tb)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/_vendor/six.py”, line 685, in reraise
> 
>         raise value.with_traceback(tb)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 154, in save_modules
> 
>         yield saved
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 195, in setup_context
> 
>         yield
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 250, in run_setup
> 
>         _execfile(setup_script, ns)
> 
>       File “/scratch/tlyons/testmanylinuxesig/py3/lib/python3.6/site-packages/setuptools/sandbox.py”, line 45, in _execfile
> 
>         exec(code, globals, locals)
> 
>       File “/tmp/easy_install-0mb05pjc/numpy-1.20.0rc2/setup.py”, line 30, in <module>
> 
>         """
> 
>     RuntimeError: Python version >= 3.7 required.

**Comment by terrylyons** [comment]
SM confirmed that the wheel worked fine on exact same setup with a current version of setup tools. A working version of setup tools should be flagged as a prerequisite for successful installation of the wheel; an intelligible error message?.

**Comment by inakleinbottle** [comment]
I think the issue is more likely to be the absence of wheel in older versions of pip. Still waiting to confirm.

**Comment by rolyp** [comment]
Bumped `sdist` job in GitHub to run on Python 3.7.
